
 import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidemenu from "./_componants/sidemenu";
import { Cairo, Barlow_Condensed } from "next/font/google";
import Footer from "./_componants/footer";
import Request from "./_componants/request";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});
const getCar = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Salaty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="ar">
      <head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </head>
       <body
        className={`${geistSans.variable} ${geistMono.className} antialiased`}
      >
         <Request />
        <div className="window flex justify-end mb-[40px]" >
         {children}
      <Sidemenu  />
          
        </div>
{/*         <Footer />
         */}
      </body>
    </html>
  );
}
